CREATE TABLE tb_user(
	 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	 login_id VARCHAR(20) NOT NULL,
	 login_password VARCHAR(20) NOT NULL,
	 `name` VARCHAR(20) NULL,
	 address VARCHAR(100) NULL,
	 phone VARCHAR(20) NULL,
	 error_count INT NOT NULL DEFAULT 0,
	 create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	 update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_board(
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(20) NOT NULL,
	content VARCHAR(20) NOT NULL,
	user_id BIGINT NOT NULL,
	create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP 
);